spring:
  application:
    name: volunteer-management-platform
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    "[com.voluntrack.volunteerplatform]": DEBUG
    "[org.springframework.security]": INFO
    "[org.hibernate.SQL]": DEBUG

  file:
    name: logs/voluntrack.log

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7