server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  thymeleaf:
    cache: true

logging:
  level:
    root: INFO
    "[com.voluntrack.volunteerplatform]": INFO
    "[org.springframework.security]": INFO